services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orders-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/Orders.Api/Dockerfile
    container_name: orders-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__OrdersDb: "Server=sqlserver,1433;Database=OrdersDb;User Id=sa;Password=Your_password123;TrustServerCertificate=true"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
